import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 指南：架构总览与技术选型
  gettingStartedSidebar: [
    {type: 'autogenerated', dirName: 'getting-started'},
  ],

  // 规范：目录、WXML、注释、RESTful、工作流等开发规范
  specificationSidebar: [
    {type: 'autogenerated', dirName: 'specification'},
  ],

  // 业务功能：认证、支付、加密、文件上传、容灾
  featuresSidebar: [
    {type: 'autogenerated', dirName: 'features'},
  ],

  // 工程化：Lint、CI/CD、测试、部署
  pipelineSidebar: [
    {type: 'autogenerated', dirName: 'pipeline'},
  ],

  // Cookbook：实用技巧与代码片段
  cookbookSidebar: [
    {type: 'autogenerated', dirName: 'cookbook'},
  ],

  // 参考：配置手册
  referenceSidebar: [
    {type: 'autogenerated', dirName: 'reference'},
  ],
};

export default sidebars;
